name: chasse_canards_front_office

services:
  front-office:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    networks:
      - chasse-canards-front-office
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./vite.config.js

networks:
  chasse-canards-front-office: